import { AppContext } from "../../../../context";
import { Server } from "../../../../lexicon";

import checkPermission from "./checkPermission";
import checkPermissions from "./checkPermissions";
import createBubble from "./createBubble";
import createGroup from "./createGroup";
import createRecord from "./createRecord";
import createRelation from "./createRelation";
import createRole from "./createRole";
import createSpace from "./createSpace";
import deleteBlob from "./deleteBlob";
import deleteBubble from "./deleteBubble";
import deleteGroup from "./deleteGroup";
import deleteRecord from "./deleteRecord";
import deleteRelation from "./deleteRelation";
import deleteRole from "./deleteRole";
import deleteSpace from "./deleteSpace";
import describeBubble from "./describeBubble";
import describeGroup from "./describeGroup";
import describeRole from "./describeRole";
import describeSpace from "./describeSpace";
import getBlob from "./getBlob";
import getBubble from "./getBubble";
import getGroup from "./getGroup";
import getRecord from "./getRecord";
import getRelation from "./getRelation";
import getRole from "./getRole";
import getSpace from "./getSpace";
import listBlobs from "./listBlobs";
import listBubbles from "./listBubbles";
import listGroups from "./listGroups";
import listMissingBlobs from "./listMissingBlobs";
import listRecords from "./listRecords";
import listRelations from "./listRelations";
import listRoles from "./listRoles";
import listSpaces from "./listSpaces";
import lookupResources from "./lookupResources";
import lookupSubjects from "./lookupSubjects";
import updateBubble from "./updateBubble";
import updateGroup from "./updateGroup";
import updateRecord from "./updateRecord";
import updateRelation from "./updateRelation";
import updateRole from "./updateRole";
import updateSpace from "./updateSpace";
import uploadBlob from "./uploadBlob";

export default function (server: Server, ctx: AppContext) {
  checkPermission(server, ctx);
  checkPermissions(server, ctx);
  createBubble(server, ctx);
  createGroup(server, ctx);
  createRecord(server, ctx);
  createRelation(server, ctx);
  createRole(server, ctx);
  createSpace(server, ctx);
  deleteBlob(server, ctx);
  deleteBubble(server, ctx);
  deleteGroup(server, ctx);
  deleteRecord(server, ctx);
  deleteRelation(server, ctx);
  deleteRole(server, ctx);
  deleteSpace(server, ctx);
  describeBubble(server, ctx);
  describeGroup(server, ctx);
  describeRole(server, ctx);
  describeSpace(server, ctx);
  getBlob(server, ctx);
  getBubble(server, ctx);
  getGroup(server, ctx);
  getRecord(server, ctx);
  getRelation(server, ctx);
  getRole(server, ctx);
  getSpace(server, ctx);
  listBlobs(server, ctx);
  listBubbles(server, ctx);
  listGroups(server, ctx);
  listMissingBlobs(server, ctx);
  listRecords(server, ctx);
  listRelations(server, ctx);
  listRoles(server, ctx);
  listSpaces(server, ctx);
  lookupResources(server, ctx);
  lookupSubjects(server, ctx);
  updateBubble(server, ctx);
  updateGroup(server, ctx);
  updateRecord(server, ctx);
  updateRelation(server, ctx);
  updateRole(server, ctx);
  updateSpace(server, ctx);
  uploadBlob(server, ctx);
}
